specVersion: "0.3.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: "avax.dc.thechainhub.com"
  port: 9650
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDc4MTYwOTMsImp0aSI6IjJHaWlkTGhEWVp5MUlMSVlIS1gzVExfWmltZz0iLCJlbmRwb2ludHMiOlsiL2V4dC9pbmRleC9DL2Jsb2NrIiwiL2V4dC9iYy9YIiwiL2V4dC9pbmZvIiwiL2V4dC9iYy9DIiwiL2V4dC9pbmRleC9YL3Z0eCIsIi9leHQvaW5kZXgveC90eCIsIi9leHQvYmMvQy9ycGMiXX0.N0xLRiEqFRuOyPw5zdudZ85y4pC8BluI0LSOw0Cd6Bo'
  genesisHash: '0x31ced5b9beb7f8782b014660da0cb18cc409f121f408186886e1ca3e8eeca96b'
  chainName: 'C'
  type: 'avalanche'
  chainId: 'mainnet'

dataSources:
  - kind: substrate/Runtime
    processor: {}
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: BlockHandler
        - handler: handleCall
          kind: CallHandler
          filter:
            - { to: '0x640440c1a691dc824c89f92a856848a9013d3784' }
            - { to: '0x95042281af6566fc6748f28263ceeecaefb4d2b4' }
        - handler: handleEvent
          kind: EventHandler
          filter:
            - { address: '0x640440c1a691dc824c89f92a856848a9013d3784' }
            - { address: '0x95042281af6566fc6748f28263ceeecaefb4d2b4' }